default: &default
  adapter: postgresql
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: friendbook_dev5

test:
  <<: *default
  database: friendbook_test5

production:
  <<: *default
  database: friendbook_prod5
