default: &default
  adapter: postgresql
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: friendbook_dev1

test:
  <<: *default
  database: friendbook_test1

production:
  <<: *default
  database: friendbook_prod1
